#!/bin/bash

quit () {
    osascript -e 'tell application "Terminal" to close (every window whose name contains ".command")' & exit
    osascript -e 'tell application "Terminal" to close first window' & exit
    osascript -e 'tell application "Terminal" to close first window' & exit
    osascript -e "do shell script \"osascript -e \\\"tell application \\\\\\\"Terminal\\\\\\\" to quit\\\" &> /dev/null &\""; exit
}

phoneNumberList=(PHONENUMBER1 PHONENUMBER2 PHONENUMBER3)
sectionList=(SECTION1 SECTION2 SECTION3)
#nameList=(OPTIONAL NAME LIST TO KEEP TRACK OF WHO IS WHO)

message=$(date '+%A, %B %-Oe')

letterDay="$(/usr/local/bin/node /Users/USERNAME/Desktop/getLetterDay.js)"

for ((i=0; i < ${#phoneNumberList[@]}; i++))
do

	filePath="/Users/USERNAME/Desktop/"${sectionList[$i]}" Schedule/"${sectionList[$i]}" Schedule "${letterDay}" Day.jpg"
	osascript -e "tell application\"Messages\" to send POSIX file \"${filePath}\" to buddy \"${phoneNumberList[$i]}\"";
	osascript -e "tell application\"Messages\" to send \"${message}\" to buddy \"${phoneNumberList[$i]}\"";
done